# This file is both GNU make and POSIX shell compatible.
PFC_RELEASE_VERSION=0.1.0
PFC_RELEASE_SOURCE=penguin-flight-console-update.tar.gz
PFC_RELEASE_SITE=https://gitee.com/ncer/penguin-flight-console/releases/download/v0.1.0
